kind: Service
apiVersion: v1
metadata:
  name:  nginx-service
spec:
  selector:
    app:  nginx
  type:  ClusterIP
  externalIPs:
    - "192.140.0.20"
  ports:
  - name:  http
    port:  8000
    targetPort:  8080
