kind: Service
apiVersion: v1
metadata:
  name:  nginx-service
spec:
  selector:
    app:  nginx
  type:  ClusterIP
  loadBalancerIP: 127.0.0.19
  ports:
  - name:  http
    port:  80
    targetPort:  8080
