kind: Service
apiVersion: v1
metadata:
  name:  nginx-service
spec:
  
  selector:
    app:  nginx
  type:  ClusterIP
  loadBalancerIP: "192.140.0.20"
  allocateLoadBalancerNodePorts: true
  ports:
  - name:  http
    port:  8000
    targetPort:  80
